### ISSUE TITLE
Decode Error

### ISSUE THREAD

**Issue by madereddy** [madereddy/noisy#5]
JSONDecode Error

```
Traceback (most recent call last):
  File "//noisy.py", line 289, in <module>
    main()
  File "//noisy.py", line 279, in main
    crawler = Crawler()
  File "//noisy.py", line 42, in __init__
    self.ua = UserAgent()
  File "/usr/local/lib/python3.9/site-packages/fake_useragent/fake.py", line 69, in __init__
    self.load()
  File "/usr/local/lib/python3.9/site-packages/fake_useragent/fake.py", line 75, in load
    self.data = load_cached(
  File "/usr/local/lib/python3.9/site-packages/fake_useragent/utils.py", line 252, in load_cached
    return read(path)
  File "/usr/local/lib/python3.9/site-packages/fake_useragent/utils.py", line 230, in read
    return json.loads(fp.read())
  File "/usr/local/lib/python3.9/json/__init__.py", line 346, in `loads`
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by madereddy** [comment]
Corrected the issue during latest release.
